sudo: false
language: node_js
node_js:
  - "io.js"
  - "0.12"
  - "0.10"
before_install:
  - npm install -g npm
before_script:
  - npm install -g grunt-cli
  - npm uninstall grunt # https://github.com/npm/npm/issues/3958
script:
  - grunt
  - grunt test