env:
  global:
    - CC_TEST_REPORTER_ID=a7bc1ef397115120c4c23d9361ae64475cd8797469cd6c2bcea7c57d70ca5e22
sudo: false
language: node_js
node_js:
  - "node"
  - "lts/*"
install:
  - npm install
  - npm install -g grunt-cli
  - npm install -g nyc
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc --reporter lcov --reporter text npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
